version: "3"

services:
  react:
    image: node:16.18-alpine
    expose:
      - "5173"
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app
    working_dir: "/app"
    entrypoint: "/usr/local/bin/yarn"
    command: "dev --host"
