version: "3"

services:
  web:
    image: productsdb/dev
    build:
      context: .
      dockerfile: app.dev.Dockerfile
    ports:
      - 80:80
    environment:
      ENV_MODE: development
    volumes:
      - ./backend:/var/www/html

  mysql:
    image: mysql:5.7-debian
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    env_file:
      - ./backend/config/db.env
    volumes:
      - ./backend/config/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      # - db:/var/lib/mysql
      - ./.db:/var/lib/mysql

  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - 8080:8080
    profiles:
      - all
      - adminer

  react:
    image: node:16.18-alpine
    expose:
      - 5173
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app
    working_dir: "/app"
    entrypoint: "/usr/local/bin/yarn"
    command: "dev --host"
    profiles:
      - all
      - react

  dist:
    image: productsdb/build
    build:
      context: .
      dockerfile: app.build.Dockerfile
    volumes:
      - ./dist:/dist
    command: cp -r /var/www/html/. /dist/
    profiles:
      - dist
# volumes:
# db:
