version: "3"

services:
  web:
    image: app/dev
    build:
      context: .
      dockerfile: app.dev.Dockerfile
    ports:
      - 80:80
    environment:
      ENV_MODE: development
    volumes:
      - ./backend:/var/www/html

  mysql:
    image: mysql:5.7-debian
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    env_file:
      - ./backend/config/db.env
    volumes:
      - ./backend/config/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - db:/var/lib/mysql

volumes:
  db:
