version: "3"

services:
  web:
    image: app/build
    build:
      context: .
      dockerfile: app.build.Dockerfile
    ports:
      - 80:80

  mysql:
    image: mysql:5.7-debian
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    env_file:
      - ./backend/config/db.env
    volumes:
      - ./backend/config/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - prod-db:/var/lib/mysql

volumes:
  prod-db:
