CREATE TABLE IF NOT EXISTS 'products' (
  'id' INTEGER PRIMARY KEY AUTOINCREMENT,
  'sku' VARCHAR(100) NOT NULL,
  'name' VARCHAR(255) NOT NULL,
  'price' DECIMAL(10,2) NOT NULL,
  'type' VARCHAR(30) NOT NULL,
  'size' DECIMAL(10,2) DEFAULT NULL,
  'width' DECIMAL(10,2) DEFAULT NULL,
  'height' DECIMAL(10,2) DEFAULT NULL,
  'length' DECIMAL(10,2) DEFAULT NULL,
  'weight' DECIMAL(10,2) DEFAULT NULL
);
